In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv(r"C:\Users\USER\Desktop\zummit feb\exercises\hotel_booking_data.csv")

In [4]:
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,name,email,phone-number,credit_card
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,Transient,0.0,0,0,Check-Out,2015-07-01,Ernest Barnes,Ernest.Barnes31@outlook.com,669-792-1661,************4322
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,Transient,0.0,0,0,Check-Out,2015-07-01,Andrea Baker,Andrea_Baker94@aol.com,858-637-6955,************9157
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,Transient,75.0,0,0,Check-Out,2015-07-02,Rebecca Parker,Rebecca_Parker@comcast.net,652-885-2745,************3734
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,Transient,75.0,0,0,Check-Out,2015-07-02,Laura Murray,Laura_M@gmail.com,364-656-8427,************5677
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,Transient,98.0,0,1,Check-Out,2015-07-03,Linda Hines,LHines@verizon.com,713-226-5883,************5498

In [5]:
df.transpose()

,0,1,2,3,4,5,6,7,8,9,...,119380,119381,119382,119383,119384,119385,119386,119387,119388,119389
hotel,Resort Hotel,Resort Hotel,Resort Hotel,Resort Hotel,Resort Hotel,Resort Hotel,Resort Hotel,Resort Hotel,Resort Hotel,Resort Hotel,...,City Hotel,City Hotel,City Hotel,City Hotel,City Hotel,City Hotel,City Hotel,City Hotel,City Hotel,City Hotel
is_canceled,0,0,0,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
lead_time,342,737,7,13,14,14,0,9,85,75,...,44,188,135,164,21,23,102,34,109,205
arrival_date_year,2015,2015,2015,2015,2015,2015,2015,2015,2015,2015,...,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017
arrival_date_month,July,July,July,July,July,July,July,July,July,July,...,August,August,August,August,August,August,August,August,August,August
arrival_date_week_number,27,27,27,27,27,27,27,27,27,27,...,35,35,35,35,35,35,35,35,35,35
arrival_date_day_of_month,1,1,1,1,1,1,1,1,1,1,...,31,31,30,31,30,30,31,31,31,29
stays_in_weekend_nights,0,0,0,0,0,0,0,0,0,0,...,1,2,2,2,2,2,2,2,2,2
stays_in_week_nights,0,0,1,1,2,2,2,2,3,3,...,3,3,4,4,5,5,5,5,5,7
adults,2,2,1,1,2,2,2,2,2,2,...,2,2,3,2,2,2,3,2,2,2
children,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
babies,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
meal,BB,BB,BB,BB,BB,BB,BB,FB,BB,HB,...,SC,BB,BB,BB,BB,BB,BB,BB,BB,HB
country,PRT,PRT,GBR,GBR,GBR,GBR,PRT,PRT,PRT,PRT,...,DEU,DEU,JPN,DEU,BEL,BEL,FRA,DEU,GBR,DEU
market_segment,Direct,Direct,Direct,Corporate,Online TA,Online TA,Direct,Direct,Online TA,Offline TA/TO,...,Online TA,Direct,Online TA,Offline TA/TO,Offline TA/TO,Offline TA/TO,Online TA,Online TA,Online TA,Online TA
distribution_channel,Direct,Direct,Direct,Corporate,TA/TO,TA/TO,Direct,Direct,TA/TO,TA/TO,...,TA/TO,Direct,TA/TO,TA/TO,TA/TO,TA/TO,TA/TO,TA/TO,TA/TO,TA/TO
is_repeated_guest,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
previous_cancellations,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
previous_bookings_not_canceled,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
reserved_room_type,C,C,A,A,A,A,C,C,A,D,...,A,A,G,A,A,A,E,D,A,A
assigned_room_type,C,C,C,A,A,A,C,C,A,D,...,A,A,G,A,A,A,E,D,A,A
booking_changes,3,4,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
deposit_type,No Deposit,No Deposit,No Deposit,No Deposit,No Deposit,No Deposit,No Deposit,No Deposit,No Deposit,No Deposit,...,No Deposit,No Deposit,No Deposit,No Deposit,No Deposit,No Deposit,No Deposit,No Deposit,No Deposit,No Deposit
agent,NaN,NaN,NaN,304.0,240.0,240.0,NaN,303.0,240.0,15.0,...,9.0,14.0,7.0,42.0,394.0,394.0,9.0,9.0,89.0,9.0
company,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
days_in_waiting_list,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
customer_type,Transient,Transient,Transient,Transient,Transient,Transient,Transient,Transient,Transient,Transient,...,Transient,Transient,Transient,Transient,Transient,Transient,Transient,Transient,Transient,Transient
adr,0.0,0.0,75.0,75.0,98.0,98.0,107.0,103.0,82.0,105.5,...,140.75,99.0,209.0,87.6,96.14,96.14,225.43,157.71,104.4,151.2
required_car_parking_spaces,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
total_of_special_requests,0,0,0,0,1,1,0,1,1,0,...,1,0,0,0,2,0,2,4,0,2
reservation_status,Check-Out,Check-Out,Check-Out,Check-Out,Check-Out,Check-Out,Check-Out,Check-Out,Canceled,Canceled,...,Check-Out,Check-Out,Check-Out,Check-Out,Check-Out,Check-Out,Check-Out,Check-Out,Check-Out,Check-Out
reservation_status_date,2015-07-01,2015-07-01,2015-07-02,2015-07-02,2015-07-03,2015-07-03,2015-07-03,2015-07-03,2015-05-06,2015-04-22,...,2017-09-04,2017-09-05,2017-09-05,2017-09-06,2017-09-06,2017-09-06,2017-09-07,2017-09-07,2017-09-07,2017-09-07
name,Ernest Barnes,Andrea Baker,Rebecca Parker,Laura Murray,Linda Hines,Jasmine Fletcher,Dylan Rangel,William Velez,Steven Murphy,Michael Moore,...,Wanda Jones,Betty Taylor,Cesar Moreno,Jose Andersen,James Mccarty,Claudia Johnson,Wesley Aguilar,Mary Morales,Caroline Conley MD,Ariana Michael
email,Ernest.Barnes31@outlook.com,Andrea_Baker94@aol.com,Rebecca_Parker@comcast.net,Laura_M@gmail.com,LHines@verizon.com,JFletcher43@xfinity.com,Rangel.Dylan@comcast.net,Velez_William@mail.com,Steven.Murphy54@aol.com,MichaelMoore81@outlook.com,...,Wanda_J@yandex.com,BTaylor@yandex.com,Cesar_M50@comcast.net,Andersen_Jose@protonmail.com,James_M@att.com,Claudia.J@yahoo.com,WAguilar@xfinity.com,Mary_Morales@hotmail.com,MD_Caroline@comcast.net,Ariana_M@xfinity.com
phone-number,669-792-1661,858-637-6955,652-885-2745,364-656-8427,713-226-5883,190-271-6743,420-332-5209,286-669-4333,341-726-5787,316-648-6176,...,379-374-7947,114-632-1395,666-379-7260,656-714-5930,689-204-7523,403-092-5582,238-763-0612,395-518-4100,531-528-1017,422-804-6403
credit_card,************4322,************9157,************3734,************5677,************5498,************9263,************6994,************8729,************3639,************9190,...,************8581,************1795,************7835,************7923,************7994,************8647,************4333,************1821,************7860,************4482

### TASK: What are the names of the people who had booked the most number children and babies for their stay? (Don't worry if they canceled, only consider number of people reported at the time of their reservation

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 36 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
 32  name                            119390 non-null  object
 33  email                           119390 non-null  object
 34  phone-number                    119390 non-null  object
 35  credit_card                     119390 non-null  object
dtypes: float64(4), int64(16), object(16)
memory usage: 32.8+ MB

In [6]:
df["total_num_of_kids"] = df["babies"] + df["children"]

In [7]:
df.sort_values("total_num_of_kids", ascending=False)[["name", "adults", "babies", "children", "total_num_of_kids"]].head(3)

                  name  adults  babies  children  total_num_of_kids
328      Jamie Ramirez       2       0      10.0               10.0
46619  Nicholas Parker       2      10       0.0               10.0
78656    Marc Robinson       1       9       0.0                9.0

# What are the top 3 most common area code in the phone numbers? (Area code is first 3 digits)

In [8]:
df["phone-number"]

0         669-792-1661
1         858-637-6955
2         652-885-2745
3         364-656-8427
4         713-226-5883
              ...
119385    403-092-5582
119386    238-763-0612
119387    395-518-4100
119388    531-528-1017
119389    422-804-6403
Name: phone-number, Length: 119390, dtype: object

In [9]:
# df["area_code"] = df["phone-number"].str.split("-")

In [10]:
def get_area_code(df):
    # for _ in range(len(df)):
    code=  df.split("-")
    return code[0]

In [11]:
df["area_code"] = df["phone-number"].apply(get_area_code)

In [12]:
df["area_code"].value_counts().head(3)

area_code
799    168
185    167
541    166
Name: count, dtype: int64

In [13]:
df['phone-number'].astype(str).str[:3].value_counts().head(3)

phone-number
799    168
185    167
541    166
Name: count, dtype: int64

In [14]:
df.isna().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
name                                   0
email                                  0
phone-number                           0
credit_card                            0
total_num_of_kids                      4
area_code                              0
dtype: int64

In [15]:
df.dropna(subset="country", inplace=True)

In [16]:
df.isna().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                                0
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16006
company                           112279
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
name                                   0
email                                  0
phone-number                           0
credit_card                            0
total_num_of_kids                      4
area_code                              0
dtype: int64